### ISSUE TITLE
make install without root permission

### ISSUE THREAD

**Issue by zpgaal** [embedthis/me#24]
At the moment it seems as makeme can be installed using root permissions only. It is not acceptable for multi-user systems (ex at a university).

me --prefix dir=/home/gzp/local install
me: ERROR: Error with target: installBinary
Command: 
                require embedthis.me
                makeme.loader.blendFile('/home/gzp/work/me-0.8.5/src/paks/me-package/manifest.me')
                Package().installBinary()
            
Must run as root. Use "sudo me install"

me: ERROR: Building target installBinary
Exiting

**Comment by embedthis** [comment]
Patch checked in and testing now. Will be released in 0.8.6 at the end of the month.
