### ISSUE TITLE
Question: Building to a different directory

### ISSUE THREAD

**Issue by SurferL** [embedthis/me#42]
I've just started exploring using MakeMe and AppWeb - and I was wondering how you would go about building the targets to a different directory? 
Currently I have something like:
`targets: {`
`        server: {`
`            type:    'exe',`
`            sources: ['*.c'],`
`            depends: ['appweb'],`
`        },`
and this would just build the server exe file into the main folder where the source is. I am unable to find documentation of where I would be able to influence where the "server.exe" and "*.o" files would be then located.
Any advice would be greatly appreciated!
Thanks

**Comment by embedthis** [comment]
You can do this multiple ways:

1. Add a 'path' like:
```
path: 'subdir/server${EXE}'
```
The ${EXE} is for windows and expands to .exe on windows and '' on other platforms.

2. Set the me.dir.bin directory and then all binaries go there. In your start.me/main.me file, define:

```
directories: {
    bin: 'any/directory'
}
```

**Comment by SurferL** [comment]
Thanks for the reply - however I think I am still missing something.
1. So my start.me file now looks something like this:
```
Me.load({
    configure: {
        requires: ['appweb'],
    },
    targets: {
        server: {
            type:    'exe',
	        path:    'bin/server${EXE}',
            sources: 'src/*.c',
            depends: ['appweb'],
        },
        run: {
            run: './server',
        },
    },
})
```
So now when compiling with `me` I get a linker failure:
```
[Link] bin/server
me: ERROR: Building target server
Command failure: /usr/bin/ld: cannot open output file bin/server: No such file or directory
```
Which bit am I missing?
2. When you say: 
```
directories: {
    bin: 'any/directory'
}
```
I don't need to give any more commands for the targets, as they would be forced into the bin directory? For example my project folder would look something like this:
```
Project
    -bin
    -html
    -src
    start.me
    index.html
    appweb.conf
```
and so setting the me.dir.bin directory would be something like:
```
directories: {
    bin: 'bin/'
}
```
Sorry for any confusion!

**Comment by embedthis** [comment]
My mistake with directories. It is "dir" not directories. So use either:

```
Me.load({
    configure: {
        requires: ['appweb'],
    },
    targets: {
        server: {
            path:    'output/server',
            type:    'exe',
            sources: '*.c',
            depends: ['appweb'],
        },
        run: {
            run: './server',
        },
    },
})
```

or

```
Me.load({
    dir: {
        bin: 'bin'
    },
    configure: {
        requires: ['appweb'],
    },
    targets: {
        server: {
            type:    'exe',
            sources: '*.c',
            depends: ['appweb'],
        },
        run: {
            run: './server',
        },
    },
})
```

NOTE: in the 2nd form, do not supply a path. The output directory will need to exist.

**Comment by SurferL** [comment]
Using the `dir` option is now working for me thanks! When building the files, they also generate a object file, however that isn't going into the bin directory?
Using `path:` however is still bringing up the same error as before...

**Comment by embedthis** [comment]
You can run with -s to show the actual command LD is running

    me -s

**Comment by SurferL** [comment]
Ah sorry, I needed to have created the output directory first! Thanks!
Concerning the object files, would I need to add additional details in `targets` so that when they are built they would also enter the `bin` directory?

**Comment by embedthis** [comment]
The object is placed at:

                        let obj = me.dir.obj.join(file.replaceExt(me.ext.o).basename)

so, add 'obj' to dir will do it.

   {
        dir: {
            obj: 'bin'
        }
    }

**Comment by SurferL** [comment]
Ah perfect, thank you very much for your help!
